modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="spawn"
version="1.20.1-1.4.0"
displayName="Spawn"
logoFile= "spawn.png"
authors="Orcinus"
description='''
An animal mod that tries to add new animals with niches and personality to the Minecraft world

Author:
- Ninni

Contributors:
- Orcinus
- lunarbunten

'''
[[dependencies.spawn]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.spawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
